version: '3'
services:
  embulk:
    build: .
    volumes:
      - ./data:/data
      - ./config:/config
      - ./keys:/keys
    command:
      [
        "/bin/bash",
        "-c",
        "embulk preview /config/embulk.yml.liquid"
      ]
