version: '3'
services:
  embulk:
    build: .
    volumes:
      - ./data:/data
      - ./config:/config
    command:
      [
        "/bin/bash",
        "-c",
        "/opt/embulk/bin/embulk preview /config/embulk.yaml"
      ]
